"""Reporting: turn a list of Findings into a shareable report.

Always emits a self-contained HTML file. If reportlab is installed it
also emits a PDF summary. No external template engine required.
"""
from __future__ import annotations

import html
import logging
from collections import Counter
from pathlib import Path
from typing import List

from ..core.schema import Finding

log = logging.getLogger("marlong.report")

_SEV_ORDER = {"high": 0, "medium": 1, "low": 2, "info": 3}
_SEV_COLOR = {"high": "#c0392b", "medium": "#e67e22", "low": "#f1c40f", "info": "#7f8c8d"}


def _sorted(findings: List[Finding]) -> List[Finding]:
    return sorted(findings, key=lambda f: (_SEV_ORDER.get(f.severity, 9), f.source))


def generate_html(scan_id: str, findings: List[Finding], out_dir: str) -> str:
    findings = _sorted(findings)
    sev_counts = Counter(f.severity for f in findings)
    src_counts = Counter(f.source for f in findings)

    rows = []
    for f in findings:
        ent = "; ".join(f"{k}: {', '.join(v)}" for k, v in f.entities.items()) or "&mdash;"
        secrets = ", ".join(f.metadata.get("secret_indicators", [])) or ""
        display_title = html.escape((f.title or f.url)[:90])
        full_url = html.escape(f.url)
        rows.append(f"""
        <tr>
          <td><span class="sev" style="background:{_SEV_COLOR.get(f.severity,'#777')}">{html.escape(f.severity)}</span></td>
          <td>{html.escape(f.source)}</td>
          <td>{html.escape(f.type)}</td>
          <td><a href="{full_url}" title="{full_url}" target="_blank" rel="noopener">{display_title}</a>
              <div class="snip">{html.escape((f.snippet or '')[:200])}</div>
              {f'<div class="secret">&#9888; secrets: {html.escape(secrets)}</div>' if secrets else ''}</td>
          <td class="ent">{html.escape(ent)}</td>
        </tr>""")

    summary = " ".join(
        f'<span class="pill" style="background:{_SEV_COLOR.get(s,"#777")}">{s}: {sev_counts[s]}</span>'
        for s in ["high", "medium", "low", "info"] if sev_counts[s]
    )
    sources = ", ".join(f"{s} ({c})" for s, c in src_counts.items())

    doc = f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="description" content="Marlong OSINT Engine report — scan {html.escape(scan_id)} — authorised use only">
<title>Marlong Report {html.escape(scan_id)}</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#f4f5f7;color:#1a1a1a}}
 header{{background:#10141a;color:#fff;padding:24px 32px}}
 header h1{{margin:0;font-size:22px;letter-spacing:.5px}}
 header .meta{{color:#9aa4b2;font-size:13px;margin-top:4px}}
 .wrap{{padding:24px 32px}}
 .pill,.sev{{color:#fff;border-radius:10px;padding:2px 10px;font-size:12px;font-weight:600}}
 .pill{{margin-right:6px}}
 table{{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1)}}
 th,td{{text-align:left;padding:10px 12px;border-bottom:1px solid #eee;font-size:13px;vertical-align:top}}
 th{{background:#fafafa;text-transform:uppercase;font-size:11px;letter-spacing:.5px;color:#555}}
 .snip{{color:#666;font-size:12px;margin-top:3px}}
 .secret{{color:#c0392b;font-weight:600;font-size:12px;margin-top:3px}}
 .ent{{color:#2c3e50;font-size:12px;max-width:280px;word-break:break-word}}
 a{{color:#2563eb;text-decoration:none}} a:hover{{text-decoration:underline}}
</style></head><body>
<header><h1>MARLONG &mdash; OSINT Report</h1>
<div class="meta">scan {html.escape(scan_id)} &middot; {len(findings)} findings &middot; sources: {html.escape(sources)}</div></header>
<div class="wrap">
 <p>{summary or '<span class="pill" style="background:#777">no findings</span>'}</p>
 <table><thead><tr><th>Severity</th><th>Source</th><th>Type</th><th>Finding</th><th>Entities</th></tr></thead>
 <tbody>{''.join(rows) or '<tr><td colspan=5>No findings.</td></tr>'}</tbody></table>
</div>
<footer style="text-align:center;padding:16px;font-size:11px;color:#9aa4b2">
  Generated by Marlong OSINT Engine &mdash; authorised use only
</footer>
</body></html>"""

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"marlong_report_{scan_id}.html"
    path.write_text(doc, encoding="utf-8")
    return str(path)


def generate_pdf(scan_id: str, findings: List[Finding], out_dir: str) -> str | None:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet
    except ImportError:
        log.info("reportlab not installed; skipping PDF report")
        return None

    findings = _sorted(findings)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"marlong_report_{scan_id}.pdf"
    doc = SimpleDocTemplate(str(path), pagesize=A4, title=f"Marlong {scan_id}")
    styles = getSampleStyleSheet()
    story = [Paragraph("MARLONG — OSINT Report", styles["Title"]),
             Paragraph(f"Scan {scan_id} · {len(findings)} findings", styles["Normal"]),
             Spacer(1, 8 * mm)]

    data = [["Sev", "Source", "Type", "Title", "URL"]]
    for f in findings:
        data.append([f.severity, f.source, f.type, (f.title or "")[:40], (f.url or "")[:45]])
    table = Table(data, colWidths=[18 * mm, 28 * mm, 26 * mm, 50 * mm, 55 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#10141a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(table)
    doc.build(story)
    return str(path)
